app:
  image: danieldent/meteor
  ports:
    - "3000:3000"
  volumes:
    - ./docroot:/app
  links:
    - "db:mongo"
  environment:
    - MONGO_URL=mongodb://mongo:27017

db:
  image: mongo
  ports:
    - "27017:27017"
